name: Static Website Tests

on:
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Check file sizes
      run: |
        echo "Checking file sizes..."
        find . -name "*.jpg" -o -name "*.png" -o -name "*.gif" | xargs ls -lh | awk '$5 > 500000 {print "WARNING: Large image file -", $9, $5}'
        
    - name: Validate HTML structure
      run: |
        echo "Checking HTML files..."
        for file in *.html; do
          if [ -f "$file" ]; then
            echo "Validating $file"
            if ! grep -q "<!DOCTYPE html>" "$file"; then
              echo "ERROR: $file missing DOCTYPE"
              exit 1
            fi
          fi
        done