name: Security and Performance Tests

on:
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sunday
  workflow_dispatch:  # Manual trigger

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Check for exposed secrets
      uses: gitleaks/gitleaks-action@v2
      
    - name: Dependency vulnerability scan
      uses: actionshub/awesome-security@main